language: python
cache:
  directories:
  - $HOME/virtualenv
services:
- postgresql
- mysql
python:
- 2.7
- 3.4
env:
- DB=postgres
- DB=mysql
install:
- pip install -r requirements/travis.txt
before_script:
- sh -c "if [ '$DB' = 'postgres' ]; then cp rdmo/settings/travis.postgres.py rdmo/settings/local.py"
- sh -c "if [ '$DB' = 'mysql' ]; then cp rdmo/settings/travis.mysql.py rdmo/settings/local.py"
script:
- coverage run manage.py test
after_success:
- coveralls
