language: python
cache:
  directories:
  - $HOME/virtualenv
services:
- postgresql
python:
- 2.7
- 3.4
install:
- pip install -r requirements/travis.txt
before_script:
- cp rdmo/settings/travis.py rdmo/settings/local.py
script:
- coverage run manage.py test
after_success:
- coveralls
