# Generated by Django 2.2.18 on 2021-04-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='imported',
            field=models.BooleanField(default=False, help_text='Designates whether this value was imported.', verbose_name='Imported'),
        ),
    ]
